name: OreGenerator
version: '${project.version}'
main: me.microdragon.oregenerator.OreGenerator
api-version: 1.19
authors: [ quangpao ]
description: A simple minecraft Plug-in to generate Ore randomly.
commands:
  oregen:
    description: Generate Ore randomly.
    usage: /oregen
    aliases: [og]
    default: true

permissions:
  oregen.reload:
    description: Reload the config file.
    default: op
  oregen.*:
    description: All permissions.
    default: op
    children:
      oregen.reload: true